POST http://localhost:3001/api/blogs
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InNwb29reUJvb2dpZSIsImlkIjoiNWVkZjdjZTdmMTRmMDI0MWU4OGQwNjJmIiwiaWF0IjoxNTkxNzA0ODU5fQ.lEos9YwVjrmotkHgPjV9PacWVjXFywQH7EQkx3si3sg

{
    "title": "Testing blog",
    "author": "Martin",
    "url": "google.com",
    "likes": 6
}